

# for compatibility with old git versions on centos
variables:
  GIT_STRATEGY: clone
  K4_JOBTYPE: Nightlies
  SPACK_VERSION: ""

stages:
    - setup_spack
    - compilation
    - deployment

setup_spack:
    stage: setup_spack
    tags:
        - k4-cvmfs
    script:
        # set up spack inside the k4-spack repo
        - if [ -n "$SPACK_VERSION" ]; then git clone  https://github.com/key4hep/spack ; cd spack; git checkout $SPACK_VERSION; cd ..; else git clone --depth 1 https://github.com/key4hep/spack; fi 
        - source spack/share/spack/setup-env.sh
        # get the right config files to the right places
        - cp config/packages.yaml spack/etc/spack/
        - mkdir spack/var/spack/repos/key4hep-spack
        - mv * spack/var/spack/repos/key4hep-spack || true
        # clean up git directories for zip
        -  rm -rf spack/.git
        # register k4 package recipes with spack
        - spack repo add --scope site ${PWD}/spack/var/spack/repos/key4hep-spack
        - zip -rqy key4hep-spack.zip spack
        - cp ${PWD}/spack/var/spack/repos/key4hep-spack/config/cvmfs_build/upstreams.yaml spack/etc/spack/
        # compiler setup 
        - spack load gcc
        - spack compiler find --scope site
        - zip -rqy key4hep-spack_centos7-cvmfs.zip spack
    artifacts:
        paths:
            - key4hep-spack_centos7-cvmfs.zip
            - key4hep-spack.zip
        expire_in: 1 week



# this job expects the following setup on the runner:
# * environment variables GITHUB_TOKEN and GITHUB_USER

#   set in .bashrc - to be able to query lates commits
# *  (for the nightlies) existing installation of key4hep-stack (stable version) in /cvmfs/sw.hsf.org/spackages
#   (or whatever is defined in upstreams.yaml)
#   this may be read-only - could be delivered by cvmfs
# * writeable directory in /cvmfs/sw-nightlies.hsf.org  / cvmfs/sw.hsf.org
#   (or whatever is defined in config.yaml)

# for the cvmfs deployment:
# * the gitlab-runner user must be able to ssh into the cvmfs publisher
# * the cvmfs publisher must be able to rsync with the build machine



# note that currently the hash of the installed dd4hep is hardcoded
# to avoid rebuilds of everything.
build-spack-nightlies:
    stage: compilation
    tags:
        - k4-build-spack-nightlies
    only:
      refs:
          - tags
          - schedules # Only execute this on scheduled "nightly" pipelines
      variables:
          - $K4_JOBTYPE == "Nightlies"
    script:
        - source spack/share/spack/setup-env.sh
        - cp ${PWD}/spack/var/spack/repos/key4hep-spack/config/cvmfs_build/config-nightlies.yaml spack/etc/spack/config.yaml
        - export K4_LATEST_SETUP_PATH=/cvmfs/sw-nightlies.hsf.org/spackages/latest/setup.sh
        # compile onwards and upwards
        - spack install key4hep-stack@master-`date -I` 



deploy-cvmfs-nightlies:
    stage: deployment
    needs: ["build-spack-nightlies"]
    tags:
        - k4-build-spack-nightlies
    only:
      refs:
          - tags
          - schedules # Only execute this on scheduled "nightly" pipelines
      variables:
          - $K4_JOBTYPE == "Nightlies"
    script:
        - ssh cvswnighthsforg@cvmfs-sw-nightlies-hsf-org.cern.ch ' bash -c ./cvmfs_deploy.sh'


build-spack-release:
    stage: compilation
    tags:
        - k4-build-spack-release
    only:
      refs:
          - tags
          - schedules # Only execute this on scheduled "nightly" pipelines
      variables:
          - $K4_JOBTYPE == "Release"
    script:
        # get the right config files to the right places
        - cp ${PWD}/spack/var/spack/repos/key4hep-spack/config/cvmfs_build/config.yaml spack/etc/spack/config.yaml
        - rm spack/etc/spack/upstreams.yaml
        - export K4_LATEST_SETUP_PATH=/cvmfs/sw.hsf.org/spackages/latest/setup.sh
        # compile onwards and upwards
        - spack install key4hep-stack@`date -I`

deploy-cvmfs-release:
    stage: deployment
    needs: ["build-spack-release"]
    tags:
        - k4-build-spack-release
    only:
      refs:
          - tags
          - schedules # Only execute this on scheduled "nightly" pipelines
      variables:
          - $K4_JOBTYPE == "Release"
    script:
        - ssh cvswhsforg@cvmfs-sw-hsf-org.cern.ch ' bash -c ./cvmfs_deploy.sh'
